#ifndef UGINE_MAIN_H
#define UGINE_MAIN_H

// FIXME: Incluirlos por componentes => hacer headers generales como "guicomponents.h"
#include "alinclude.h"
#include "array.h"
#include "audiobuffer.h"
#include "audioengine.h"
#include "audiolistener.h"
#include "audiosource.h"
#include "bone.h"
#include "camera.h"
//#include "collisionpixeldata.h"
#include "emitter.h"
#include "file.h"
#include "font.h"
#include "glinclude.h"
#include "image.h"
#include "isometricmap.h"
#include "isometricscene.h"
#include "isometricsprite.h"
#include "label.h"
#include "map.h"
#include "mapscene.h"
#include "math.h"
#include "vector2d.h"
#include "parallaxscene.h"
#include "particle.h"
#include "renderer.h"
#include "resourcemanager.h"
#include "scene.h"
#include "screen.h"
#include "skeletonsprite.h"
#include "sprite.h"
#include "string.h"
#include "types.h"
#include "inputmanager.h"
#include "guimanager.h"
#include "button.h"
#include "window.h"
#include "ieventlistener.h"
#include "checkbox.h"

#endif
